spring.application.name=hairbusiness
serve.port = 8080


#Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.main.allow-circular-references=true

#Hibernate settings
#none if want to use schema.sql not hibernate
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.default_schema=hair_business
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

## Specify locations for schema and data SQL scripts
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.mode=always

## Management endpoints
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

## Jackson serialization
#spring.jackson.serialization.fail-on-empty-beans=false

## Multipart file settings
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB

# Logging levels
#logging.level.org.hibernate.SQL=DEBUG
##logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.jdbc.datasource.init=DEBUG
##logging.level.org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory=DEBUG
##logging.level.org.springframework=INFO
#logging.level.com.example.hair_business=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG