-- INSERT INTO  hair_business.customers (is_removed,customer_id, phone_number, email, full_name )
-- VALUES
--     ("false", 1,59596987, "jj@gmail.com", "Joyceline Marealle"),
--     ("false", 2,3456789, "em@gmail.com", "Eva Marealle")